### ISSUE TITLE
ImportError: cannot import name 'Clipboard' from 'flox' 

### ISSUE THREAD

**Issue by paradox00** [Garulf/HA-Commander#27]
Python Path: 
Date: 01/13/2022 17:17:06
Exception:
```
System.IO.InvalidDataException: HA-Commander|Traceback (most recent call last):
  File "C:\Users\aviv\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-3.0.3\main.py", line 10, in <module>
    from plugin.main import Commander
  File "C:\Users\aviv\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-3.0.3\plugin\main.py", line 7, in <module>
    from flox import Flox, Clipboard
ImportError: cannot import name 'Clipboard' from 'flox' (C:\Users\aviv\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-3.0.3\lib\flox\__init__.py)
```

**Comment by Garulf** [comment]
Sorry about that, and thank you for bringing the issue to my attention. I've updated the tests to catch errors like this before they're published.

The fi is released here: https://github.com/Garulf/HA-Commander/releases/tag/v3.0.4
