### ISSUE TITLE
Flow Crashed because of HA Comander 

### ISSUE THREAD

**Issue by KrOnAsK** [Garulf/HA-Commander#41]
Hi, the Flow Launcher crashed and it told me to open a new issue here

2. copy below exception message

Flow Launcher version: 1.13.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\krona\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: C:\Users\krona\AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 02/19/2023 23:30:54
Exception:
HA-Commander Exception: 
Websites: https://github.com/Garulf/HA-Commander
Author: Garulf
Version: 5.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: C:\Users\krona\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-5.0.1\lib\urllib3\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host '******.duckdns.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

 ---> System.IO.InvalidDataException: C:\Users\krona\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-5.0.1\lib\urllib3\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host '*****.duckdns.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 811
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 785
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.
[2023-02-19.txt](https://github.com/Garulf/HA-Commander/files/10778153/2023-02-19.txt)
ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Do you have an invalid SSL certificate? While not recommended you can have the plugin skip very verification in the plugin settings.

**Comment by KrOnAsK** [comment]
No I should have a valid SSL certificate, but where could I find that out?

**Comment by Garulf** [comment]
You can quickly test if this is the case by turning verification off in HA Commander's plugin settings. If you don't get this error then it's the certificate.

**Comment by Garulf** [comment]
Try going to the address in your browser and see if any errors appear. You should be able to check the certificate by clicking the padlock icon in most browsers.

**Comment by KrOnAsK** [comment]
My certificate is valid and my connection is secure.

**Comment by KrOnAsK** [comment]
Yes thank you I did that and now its working, ty very much

**Comment by Garulf** [comment]
Glad its working now! Thanks for bringing this to my attention as I thought I had this fixed before but must have reverted it.
